### PR TITLE
Follow up on renaming vcs_PullRequestCommitAssociation to vcs_PullRequestCommit

### PR DESCRIPTION
**Pull request by tovbinm**
# Description

Follow up on #169 and depends on https://github.com/faros-ai/faros-events-cli/pull/77

## Type of change
- Bug fix (non-breaking change which fixes an issue)

# Checklist
- [x] Have you checked to there aren't other open Pull Requests for the same update/change?
- [x] Have you lint your code locally before submission?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by tovbinm** [comment]
Depends on https://github.com/faros-ai/faros-events-cli/pull/77

**Comment by ypc-faros** [comment]
> Depends on [faros-ai/faros-events-cli#77](https://github.com/faros-ai/faros-events-cli/pull/77)

Merged and released faros-events-cli:0.5.2

**Review by ypc-faros — APPROVED** [review]
Thanks!

Made some changes:

- The pkey is still `vcs_PullRequestCommitAssociation_pkey`. Added a migration.
- Renamed the mutation file (that's what we use as endpoint name, I'll document this somewhere)

**Comment by tovbinm** [comment]
Don't rename migration files. It will break. Please read the flyway docs on this. 

Generally a safe migration os to add a file and alter previous change in it. All the other cases are difficult.

**Comment by tovbinm** [comment]
OK, let's merge

**Comment by tovbinm** [comment]
If the cli was released, then rerunning the test should pass

**Comment by ypc-faros** [comment]
> Don't rename migration files. It will break. Please read the flyway docs on this.
> 
> Generally a safe migration is to add a file and alter previous change in it. All the other cases are difficult.

It's a new migration file

**Comment by ypc-faros** [comment]
> If the cli was released, then rerunning the test should pass and then we can merge

The integ tests in the PR workflow won't pass, because the events-cli now hits the new [endpoint -- vcs_pull_request_commit](https://github.com/faros-ai/faros-events-cli/blob/main/faros_event.sh#L526) and this endpoint doesn't exist in the latest faros-ce image.

OTOH, The integ test in the release workflow should pass, since the endpoint is added (via renaming the .gql file) in this PR.

**Pull request merged**
