### PR TITLE
feat: add tables for support github teams

### PR DESCRIPTION
**Pull request by jaorr95**
# Description
Add schema to support to `teams` and `teams_memberships` stream.

Related PR: https://github.com/faros-ai/airbyte-connectors/pull/1112

## Type of change
(Delete what does not apply)
- New feature (non-breaking change which adds functionality)

# Checklist
(Delete what does not apply)
- [x] Have you checked to there aren't other open Pull Requests for the same update/change?
- [x] Have you lint your code locally before submission?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by thomas-gerber** [comment]
Thank you for your contribution @jaorr95 ; 
@ted-faros I am thinking of recommending changes to keep the CE models a **subset** of our paid product, so that we can **easily** automate schema upgrades in the future.
i.e. 
* vcs_Team: 
  * remove slug, privacy, url
  * base id on source, uid
* vcs_TeamMember:
  * rename to vcs_TeamMembership
  * remove state, role, source
@ted-faros what do you think?
@jaorr95 would that be acceptable?

**Comment by ted-faros** [comment]
@thomas-gerber I agree.

**Comment by jaorr95** [comment]
@thomas-gerber i made the changes that you suggested

**Comment by thomas-gerber** [comment]
Confirmed that it upgrades properly.

**Review by thomas-gerber — APPROVED** [review]
Verified the compatibility with our data models
Verified it upgrades properly

**Pull request merged**
