### PR TITLE
Airbyte 39

### PR DESCRIPTION
**Pull request by thomas-gerber**
# Description

Upgrades to Airbyte 39.

## Type of change
- New feature (non-breaking change which adds functionality)

# Checklist
(Delete what does not apply)
- [x] Have you checked to there aren't other open Pull Requests for the same update/change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by thomas-gerber** [comment]
@cjwooo what do you think simply changing the VERSION file in the airbyte config and keep the files in there as is?

**Comment by thomas-gerber** [comment]
Tested locally on M1 on a fresh install with multiple sources. 

@cjwooo I see the following messages repeating a few times in a row when launching `start.sh`. Do you have a suggestion on what to do?
```
WARN[0000] The "NEW_SCHEDULER" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SECRET_PERSISTENCE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "WORKER_ENVIRONMENT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "RUN_DATABASE_MIGRATION_ON_STARTUP" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DEPLOYMENT_MODE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SECRET_PERSISTENCE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "WORKER_ENVIRONMENT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "JOB_ERROR_REPORTING_SENTRY_DSN" variable is not set. Defaulting to a blank string. 
WARN[0000] The "RUN_DATABASE_MIGRATION_ON_STARTUP" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DEPLOYMENT_MODE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SECRET_PERSISTENCE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "WORKER_ENVIRONMENT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "JOB_ERROR_REPORTING_SENTRY_DSN" variable is not set. Defaulting to a blank string.
```

**Comment by thomas-gerber** [comment]
@cjwooo any idea why the 'check connection to the Faros destination' tests is failing consistently? The API call seem unchanged.

**Review by cjwooo — CHANGES_REQUESTED** [review]
For the remaining env vars that are throwing a warning, you can set them explicitly to their default values, which I find by usually just grepping for the name in the main airbyte repo.

**Comment by cjwooo** [comment]
@thomas-gerber The integration test was failing because it was using the existing published faros-init image, which tries to import an Airbyte workspace with version 0.35.5, which is not incompatible with this new Airbyte version. I changed the docker-compose to build the faros-init image from scratch, https://github.com/faros-ai/faros-community-edition/pull/203/commits/173c107aa59b13cb12575536642c0be117516a4d, and now the tests pass. Once the faros-init image from this PR is published, then that commit can be reverted.

**Comment by thomas-gerber** [comment]
> @thomas-gerber The integration test was failing because it was using the existing published faros-init image, which tries to import an Airbyte workspace with version 0.35.5, which is not incompatible with this new Airbyte version. I changed the docker-compose to build the faros-init image from scratch, [173c107](https://github.com/faros-ai/faros-community-edition/commit/173c107aa59b13cb12575536642c0be117516a4d), and now the tests pass. Once the faros-init image from this PR is published, then that commit can be reverted.
> 
> This will probably not be the only time we encounter this sort of issue, so ideally our test workflow could override its copy of the docker-compose file to always build the faros-init image from scratch.

Oh makes total sense, I forgot that we do not systemically rebuild init. Thanks!

**Review by cjwooo — APPROVED** [review]

**Pull request merged**
