### PR TITLE
Disable github organizations and pull request stats streams

### PR DESCRIPTION
**Pull request by cjwooo**

### CODE REVIEW

**Review by tovbinm — APPROVED** [review]

**Comment by tovbinm** [comment]
@cjwooo What about all the other streams? e.g events, commit comments. Did you revisit them? We dont want to sync anything non essential by default

**Comment by cjwooo** [comment]
We already do not sync anything that isn't included in our models. What else is non-essential
image

**Comment by cjwooo** [comment]
I'm disabling the streams not used in our dashboard templates.

**Comment by cjwooo** [comment]
@thomas-gerber

**Pull request merged**
