### PR TITLE
Add source and connection for all supported sources in Airbyte

### PR DESCRIPTION
**Pull request by thomas-gerber**
# Description

All supported sources now have a canned source and a corresponding connection to the Faros destination in Airbyte.

Related to #195 

Screen Shot 2022-07-07 at 4 42 38 PM

## Type of change
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

# Checklist
- [x] Have you checked to there aren't other open Pull Requests for the same update/change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by thomas-gerber** [comment]
Documentation is up-to-date: https://community.faros.ai/docs/supported-sources

**Comment by ypc-faros** [comment]
nit: Do we want to also sort the sources as we did the connections
Screen Shot 2022-07-08 at 8 42 44 AM
?

**Comment by ypc-faros** [comment]
I see you added the "Faros Feeds" source to init/resources/airbyte/workspace/airbyte_config/STANDARD_SOURCE_DEFINITION.yaml but it doesn't show up in the sources tab and there's no connection set up with that source. Is that intentional?

**Comment by thomas-gerber** [comment]
> I see you added the "Faros Feeds" source to init/resources/airbyte/workspace/airbyte_config/STANDARD_SOURCE_DEFINITION.yaml but it doesn't show up in the sources tab and there's no connection set up with that source. Is that intentional?

Yes. Keeping the GH fork for now as it messes up some dashboards.

**Review by ypc-faros — APPROVED** [review]

**Pull request merged**
