### PR TITLE
Test CLA workflow

### PR DESCRIPTION
**Pull request by ogusak**
# Description

No op change to test CLA assistant
Fixes # (issue)

## Type of change
No-op

### CODE REVIEW

**Comment by tovbinm** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by tovbinm** [comment]
recheck

**Comment by ogusak** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ogusak** [comment]
@tovbinm - we have to have this 
```
  issue_comment:
    types: [created]
```
to rerun on comment :)  - creating PR

**Comment by ogusak** [comment]
https://github.com/faros-ai/faros-community-edition/pull/218

**Comment by tovbinm** [comment]
recheck

**Pull request closed without merging**
