### PR TITLE
Single compose file

### LINKED ISSUE #173: Unable to install faros on windows OS
Error:
Error response from daemon: create tmp\airbyte_local: "tmp\\airbyte_local" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path

### PR DESCRIPTION
**Pull request by thomas-gerber**
# Description

On windows, one sees local volume related errors (see #173 and [this slack thread](https://faroscommunity.slack.com/archives/C0335HMN2NQ/p1663790695205979)). However, we noticed that:
1. on that same machine, one could start vanilla airbyte with docker compose (see [airbyte documentation](https://docs.airbyte.com/deploying-airbyte/local-deployment/#setup--launch-airbyte))
2. on that same machine, `docker-compose -f airbyte-services.yaml up` did not have any volume issues (i.e. airbyte-server got successfully created.

Hence, there may be some issues with the `extends` keyword, which is not surprising given its checkered history ([here](https://docs.docker.com/compose/extends/#extending-services), and [here](https://github.com/moby/moby/issues/31101)).

The fix is to group everything into a single compose file. 
Fixes #173 
## Type of change
- Bug fix (non-breaking change which fixes an issue)

# Checklist
(Delete what does not apply)
- [x] Have you checked to there aren't other open Pull Requests for the same update/change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by thomas-gerber** [comment]
Currently being tested by a windows user.

**Comment by thomas-gerber** [comment]
Tested on
* Windows 10.0.19044 (Windows 10 Pro)
* Docker Desktop for Windows 4.12.0 (85629) with WSL2 as doc suggests (I was prompted by docker desktop to do [this](https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package)
Ingested some data.
It works!

**Comment by thomas-gerber** [comment]
@ypc-faros could you check if I got the `profiles` correct?

**Review by tovbinm — COMMENTED** [review]
Awesome!

Let's put comments around the section from the original Airbyte compose file so it would be easier for us to merge with upstream later on.

**Comment by thomas-gerber** [comment]
> Awesome!
> 
> Let's put comments around the section from the original Airbyte compose file so it would be easier for us to merge with upstream later on.

Already done

**Comment by ypc-faros** [comment]
> @ypc-faros could you check if I got the `profiles` correct?

Looks good 👍

**Review by ypc-faros — APPROVED** [review]

**Pull request merged**
