### PR TITLE
FAI-3545 - test CLA workflow - disable recheck

### PR DESCRIPTION
**Pull request by willmarks**
# Description

Testing CLA assistant. Removing recheck option to retrigger workflow
Fixes # (issue)

## Type of change
CI workflow

### CODE REVIEW

**Comment by willmarks** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by tovbinm** [comment]
recheck

**Comment by ogusak** [comment]
recheck

**Comment by ogusak** [comment]
recheck

**Comment by ogusak** [comment]
recheck

**Comment by ogusak** [comment]
recheck

**Comment by ogusak** [comment]
recheck

**Pull request closed without merging**
